server:
  port: 8081
  servlet:
    context-path: /resource-server

spring:
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: //localhost:8083/auth/realms/vita
          jwk-set-uri: http://localhost:8083/auth/realms/vita/protocol/openid-connect/certs
